### ISSUE TITLE
Could not deploy the bot using webhook

### ISSUE THREAD

**Issue by aahnik** [xon-dev/heroku_bot_tst#1]
Polling worked fine for a few seconds and then crashed.

I have set the environment variables as follows:

`TOKEN` ( token from BotFather )
, `PROJ` ( name of Heroku project )

 AND `HEROKU` ( valueless )

After deploying,

```
2020-11-21T16:06:33.939710+00:00 heroku[web.1]: State changed from crashed to starting
2020-11-21T16:06:38.339135+00:00 heroku[web.1]: Starting process with command `python bot.py`
2020-11-21T16:06:42.115941+00:00 heroku[web.1]: Process exited with status 1
2020-11-21T16:06:42.169072+00:00 heroku[web.1]: State changed from starting to crashed
2020-11-21T16:06:41.819141+00:00 app[web.1]: INFO:aiogram:Bot: AahnikTester [@aahniks_tester_bot]
2020-11-21T16:06:41.987742+00:00 app[web.1]: WARNING:aiogram:Updates were skipped successfully.
2020-11-21T16:06:41.990985+00:00 app[web.1]: ERROR:asyncio:unhandled exception during asyncio.run() shutdown
2020-11-21T16:06:41.990986+00:00 app[web.1]: task: <Task finished name='Task-6' coro=<_run_app() done, defined at /app/.heroku/python/lib/python3.8/site-packages/aiohttp/web.py:287> exception=TypeError('on_startup() takes 0 positional arguments but 1 was given')>
2020-11-21T16:06:41.990986+00:00 app[web.1]: Traceback (most recent call last):
2020-11-21T16:06:41.990987+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/aiohttp/web.py", line 508, in run_app
2020-11-21T16:06:41.990987+00:00 app[web.1]:     loop.run_until_complete(main_task)
2020-11-21T16:06:41.990988+00:00 app[web.1]:   File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
2020-11-21T16:06:41.990988+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/aiohttp/web.py", line 319, in _run_app
2020-11-21T16:06:41.990989+00:00 app[web.1]:     await runner.setup()
2020-11-21T16:06:41.990990+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/aiohttp/web_runner.py", line 275, in setup
2020-11-21T16:06:41.990990+00:00 app[web.1]:     self._server = await self._make_server()
2020-11-21T16:06:41.990990+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/aiohttp/web_runner.py", line 375, in _make_server
2020-11-21T16:06:41.990991+00:00 app[web.1]:     await self._app.startup()
2020-11-21T16:06:41.990991+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/aiohttp/web_app.py", line 416, in startup
2020-11-21T16:06:41.990992+00:00 app[web.1]:     await self.on_startup.send(self)
2020-11-21T16:06:41.990992+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/aiohttp/signals.py", line 34, in send
2020-11-21T16:06:41.990993+00:00 app[web.1]:     await receiver(*args, **kwargs)  # type: ignore
2020-11-21T16:06:41.990993+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/aiogram/utils/executor.py", line 250, in _wrap_callback
2020-11-21T16:06:41.990993+00:00 app[web.1]:     return await cb(self.dispatcher)
2020-11-21T16:06:41.990994+00:00 app[web.1]: TypeError: on_startup() takes 0 positional arguments but 1 was given
2020-11-21T16:06:41.991678+00:00 app[web.1]: Traceback (most recent call last):
2020-11-21T16:06:41.991741+00:00 app[web.1]:   File "bot.py", line 45, in <module>
2020-11-21T16:06:41.992057+00:00 app[web.1]:     executor.start_webhook(
2020-11-21T16:06:41.992112+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/aiogram/utils/executor.py", line 98, in start_webhook
2020-11-21T16:06:41.992386+00:00 app[web.1]:     executor.run_app(**kwargs)
2020-11-21T16:06:41.992389+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/aiogram/utils/executor.py", line 282, in run_app
2020-11-21T16:06:41.992703+00:00 app[web.1]:     web.run_app(self._web_app, **kwargs)
2020-11-21T16:06:41.992706+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/aiohttp/web.py", line 508, in run_app
2020-11-21T16:06:41.993089+00:00 app[web.1]:     loop.run_until_complete(main_task)
2020-11-21T16:06:41.993090+00:00 app[web.1]:   File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
2020-11-21T16:06:41.993309+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/aiohttp/web.py", line 319, in _run_app
2020-11-21T16:06:41.993604+00:00 app[web.1]:     await runner.setup()
2020-11-21T16:06:41.993607+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/aiohttp/web_runner.py", line 275, in setup
2020-11-21T16:06:41.993862+00:00 app[web.1]:     self._server = await self._make_server()
2020-11-21T16:06:41.993865+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/aiohttp/web_runner.py", line 375, in _make_server
2020-11-21T16:06:41.994180+00:00 app[web.1]:     await self._app.startup()
2020-11-21T16:06:41.994186+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/aiohttp/web_app.py", line 416, in startup
2020-11-21T16:06:41.994510+00:00 app[web.1]:     await self.on_startup.send(self)
2020-11-21T16:06:41.994534+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/aiohttp/signals.py", line 34, in send
2020-11-21T16:06:41.994724+00:00 app[web.1]:     await receiver(*args, **kwargs)  # type: ignore
2020-11-21T16:06:41.994724+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/aiogram/utils/executor.py", line 250, in _wrap_callback
2020-11-21T16:06:41.994977+00:00 app[web.1]:     return await cb(self.dispatcher)
2020-11-21T16:06:41.995020+00:00 app[web.1]: TypeError: on_startup() takes 0 positional arguments but 1 was given

```

I am looking for an example of aiogram's deployment to heroku using webhook.

**Comment by aahnik** [comment]
the code in this repo has some errors

for more refer this https://stackoverflow.com/questions/65007838/failing-to-deploy-a-aiogram-python-bot-in-webhook-mode/65021176#65021176
